version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Library.API/Dockerfile
    ports:
      - "5000:80" 
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
     - 14333:1433
    environment:
        SA_PASSWORD: "p@ssword1"
        ACCEPT_EULA: "Y"